<html><title>Exasol Error Catalog â€“ F-ETC-5</title><head><link rel="stylesheet" href="../error-catalog-style.css"></head><body><a href="../index.html"><div id="navbar"><span>Exasol Error Catalog</span></div></a><div id="mainBox"><h1>F-ETC-5</h1><h4>Message</h4><div class="code">Exasol container start-up timed out trying connection to <span class="param" nr="0">{{url}}</span> using query <span class="param" nr="1">{{query}}</span> after <span class="param" nr="2">{{after}}</span> seconds. Last connection exception was: <span class="param" nr="3">{{exception}}</span></div><h4>Parameters</h4><table><tr><td><span class="param" nr="3">exception</span></td><td>exception thrown on last connection attempt</td></tr><tr><td><span class="param" nr="2">after</span></td><td><span class="no-description">No description</span></td></tr><tr><td><span class="param" nr="1">query</span></td><td>Query used to test the connection</td></tr><tr><td><span class="param" nr="0">url</span></td><td>JDBC URL of the connection to the Exasol Testcontainer</td></tr></table><h4>Source</h4><a href="https://github.com/exasol/exasol-testcontainers/blob/7.1.1/src/main/java/com/exasol/containers/ExasolContainer.java#L742"><code>src/main/java/com/exasol/containers/ExasolContainer.java:742</code></a></div></body></html>